<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCydjacx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCydjacx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCydjacx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCydjacx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCydjacx\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cydjacx',
    'container.build_id' => '10966d21',
    'container.build_time' => 1638958121,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCydjacx');
